version: '2'
services:
    backend:
        build: .
        container_name: "backend"
        environment:
            - NODE_ENV=production
            - MONGO_URL=mongodb://mongodb:27017/photos
            - FLICKR_KEY=
            - FACEPP_KEY=
            - FACEPP_SECRET=
            - FLICKR_ALBUM_ID=72157674388093532
            - FLICKR_USER_ID=144522605@N06
            - FLICKR_TAG=int20h
            - PORT=80
        ports:
            - 80:80
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet